[package]
name = "pick_def_app"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.8.0", package = "libadwaita", features = ["v1_7"] }
freedesktop-desktop-entry = "0.7.14"
gtk = { version = "0.10.1", package = "gtk4", features = ["v4_18", "blueprint"] }
